project_id = "wczgqokhrlzbvhjpgebo"

[functions.generate-cartoon]
verify_jwt = true

[functions.analyze-story]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-answers]
verify_jwt = true

[functions.get-realtime-token]
verify_jwt = false

[functions.filter-conversation]
verify_jwt = true

[functions.biography-chat]
verify_jwt = false

[functions.get-elevenlabs-signed-url]
verify_jwt = false
