project_id = "wczgqokhrlzbvhjpgebo"

[functions.generate-cartoon]
verify_jwt = true

[functions.analyze-story]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-answers]
verify_jwt = true

[functions.get-realtime-token]
verify_jwt = false
